import type { Product, Category } from "./types";

/** REAL KraftyBrix catalogue — names, prices & images sourced from kraftybrix.in. */
export const products: Product[] = [
  {
    id: "kb-000",
    slug: "thar-black",
    name: "Thar Black",
    brand: "KraftyBrix",
    category: "SUVs & Trucks",
    tagline: "Conquer the shelf and the trail.",
    description: "The Thar Black is a collector-grade brick-built model — 240 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 999,
    salePrice: 499,
    rating: 4.9,
    reviewCount: 412,
    pieces: 240,
    buildHours: 1,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#15171A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/THR_BLK_034_1774840907005_s52obi4pdf29qz7.jpg", alt: "Thar Black" }],
    whatsIncluded: ["240 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "240" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~1 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-001",
    slug: "lambo-luminara-koenigsegg-one-1",
    name: "Lambo Luminara / Koenigsegg One:1",
    brand: "KraftyBrix",
    category: "Hypercars",
    tagline: "Brick-built hypercar fury.",
    description: "The Lambo Luminara / Koenigsegg One:1 is a collector-grade brick-built model — 1100 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 3399,
    salePrice: 1699,
    rating: 4.8,
    reviewCount: 367,
    pieces: 1100,
    buildHours: 5,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: true,
    isNew: false,
    limited: false,
    bodyColor: "#E0A21A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/LAM_LUM_001_1774840867841_qs68brauku8ez5n.jpg", alt: "Lambo Luminara / Koenigsegg One:1" }],
    whatsIncluded: ["1100 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "1,100" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~5 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-002",
    slug: "kb-defensor-orange",
    name: "KB Defensor Orange",
    brand: "KraftyBrix",
    category: "Smoking Cars",
    tagline: "Pull-back power with a real smoke-effect exhaust.",
    description: "The KB Defensor Orange is a collector-grade brick-built model — 300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1399,
    salePrice: 699,
    rating: 4.7,
    reviewCount: 289,
    pieces: 300,
    buildHours: 2,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#FF6A00",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/DEF_ORG_030_1774840965641_zkgve5xs8rbt71l.jpg", alt: "KB Defensor Orange" }],
    whatsIncluded: ["300 premium ABS bricks", "Pull-back motor + smoke-effect exhaust", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "300" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~2 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-003",
    slug: "1930s-american-hot-rod-ford",
    name: "1930s American Hot-Rod Ford",
    brand: "KraftyBrix",
    category: "Racing Cars",
    tagline: "Track-bred, fully exposed aero.",
    description: "The 1930s American Hot-Rod Ford is a collector-grade brick-built model — 560 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 2599,
    salePrice: 1299,
    rating: 5.0,
    reviewCount: 156,
    pieces: 560,
    buildHours: 4,
    difficulty: "Intermediate",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#FF6A00",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/FOR_HOT_014_1774840908174_xmdahhyj9hpiiir.jpg", alt: "1930s American Hot-Rod Ford" }],
    whatsIncluded: ["560 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "560" }, { label: "Difficulty", value: "Intermediate" }, { label: "Build time", value: "~4 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-004",
    slug: "orange-mustang",
    name: "Orange Mustang",
    brand: "KraftyBrix",
    category: "Supercars",
    tagline: "A supercar icon, brick by brick.",
    description: "The Orange Mustang is a collector-grade brick-built model — 1100 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 3399,
    salePrice: 1699,
    rating: 4.8,
    reviewCount: 98,
    pieces: 1100,
    buildHours: 5,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#FF6A00",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/FOR_MUS_008_1774840923228_zczkitia1u0m6zc.jpg", alt: "Orange Mustang" }],
    whatsIncluded: ["1100 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "1,100" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~5 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-005",
    slug: "thar-red",
    name: "Thar Red",
    brand: "KraftyBrix",
    category: "SUVs & Trucks",
    tagline: "Conquer the shelf and the trail.",
    description: "The Thar Red is a collector-grade brick-built model — 240 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 999,
    salePrice: 499,
    rating: 4.9,
    reviewCount: 204,
    pieces: 240,
    buildHours: 1,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: true,
    isNew: false,
    limited: false,
    bodyColor: "#D11B2A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/THR_RED_033_1774840872530_achxwp7des4e07h.jpg", alt: "Thar Red" }],
    whatsIncluded: ["240 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "240" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~1 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-006",
    slug: "cobra-racing-car-red",
    name: "Cobra Racing Car Red",
    brand: "KraftyBrix",
    category: "Racing Cars",
    tagline: "Track-bred, fully exposed aero.",
    description: "The Cobra Racing Car Red is a collector-grade brick-built model — 300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1399,
    salePrice: 699,
    rating: 4.7,
    reviewCount: 176,
    pieces: 300,
    buildHours: 2,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#D11B2A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/COB_RED_026_1774840936297_24jl679sfrq1ojo.jpg", alt: "Cobra Racing Car Red" }],
    whatsIncluded: ["300 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "300" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~2 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-007",
    slug: "mclaren-senna-gtr",
    name: "McLaren Senna GTR",
    brand: "KraftyBrix",
    category: "Racing Cars",
    tagline: "Track-bred, fully exposed aero.",
    description: "The McLaren Senna GTR is a collector-grade brick-built model — 620 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1899,
    salePrice: 1199,
    rating: 4.9,
    reviewCount: 243,
    pieces: 620,
    buildHours: 3,
    difficulty: "Intermediate",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: true,
    limited: false,
    bodyColor: "#FF6A00",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/McLaren_Senna_GTR_JL678LHNAV_2026-04-29_1.png", alt: "McLaren Senna GTR" }],
    whatsIncluded: ["620 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "620" }, { label: "Difficulty", value: "Intermediate" }, { label: "Build time", value: "~3 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-008",
    slug: "deep-wonderer-black",
    name: "Deep Wonderer Black",
    brand: "KraftyBrix",
    category: "Smoking Cars",
    tagline: "Pull-back power with a real smoke-effect exhaust.",
    description: "The Deep Wonderer Black is a collector-grade brick-built model — 300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1399,
    salePrice: 699,
    rating: 4.6,
    reviewCount: 131,
    pieces: 300,
    buildHours: 2,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#15171A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/DWR_BLK_028_1774840897667_fnv7j0zq9vmyjmq.jpg", alt: "Deep Wonderer Black" }],
    whatsIncluded: ["300 premium ABS bricks", "Pull-back motor + smoke-effect exhaust", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "300" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~2 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-009",
    slug: "deep-wonderer-blue",
    name: "Deep Wonderer Blue",
    brand: "KraftyBrix",
    category: "Smoking Cars",
    tagline: "Pull-back power with a real smoke-effect exhaust.",
    description: "The Deep Wonderer Blue is a collector-grade brick-built model — 300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1399,
    salePrice: 699,
    rating: 4.8,
    reviewCount: 88,
    pieces: 300,
    buildHours: 2,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#1466D6",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/DWR_BLU_029_1774840954257_03i8tlhw7voa0d9.jpg", alt: "Deep Wonderer Blue" }],
    whatsIncluded: ["300 premium ABS bricks", "Pull-back motor + smoke-effect exhaust", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "300" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~2 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-010",
    slug: "cyber-punk-suv-purple-and-blue",
    name: "Cyber Punk SUV Purple and Blue",
    brand: "KraftyBrix",
    category: "SUVs & Trucks",
    tagline: "Conquer the shelf and the trail.",
    description: "The Cyber Punk SUV Purple and Blue is a collector-grade brick-built model — 1750 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 4399,
    salePrice: 2199,
    rating: 4.9,
    reviewCount: 322,
    pieces: 1750,
    buildHours: 6,
    difficulty: "Master",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#1466D6",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/SUV_CYP_012_1774840904700_jerl0dvvp6uyqt9.jpg", alt: "Cyber Punk SUV Purple and Blue" }],
    whatsIncluded: ["1750 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "1,750" }, { label: "Difficulty", value: "Master" }, { label: "Build time", value: "~6 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-011",
    slug: "discovery-x-land-rover-defender",
    name: "Discovery X / Land Rover Defender",
    brand: "KraftyBrix",
    category: "SUVs & Trucks",
    tagline: "Conquer the shelf and the trail.",
    description: "The Discovery X / Land Rover Defender is a collector-grade brick-built model — 620 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1899,
    salePrice: 1199,
    rating: 4.8,
    reviewCount: 140,
    pieces: 620,
    buildHours: 3,
    difficulty: "Intermediate",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#2F3B2F",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/LRD_DEF_011_1774840923339_w1k1zfhwa3cgiqd.jpg", alt: "Discovery X / Land Rover Defender" }],
    whatsIncluded: ["620 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "620" }, { label: "Difficulty", value: "Intermediate" }, { label: "Build time", value: "~3 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-012",
    slug: "kb-defensor-leaf-green",
    name: "KB Defensor Leaf Green",
    brand: "KraftyBrix",
    category: "Smoking Cars",
    tagline: "Pull-back power with a real smoke-effect exhaust.",
    description: "The KB Defensor Leaf Green is a collector-grade brick-built model — 300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1399,
    salePrice: 699,
    rating: 4.7,
    reviewCount: 95,
    pieces: 300,
    buildHours: 2,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#2FA84F",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/DEF_GRN_031_1774840943450_wb2zk047gb8vyux.jpg", alt: "KB Defensor Leaf Green" }],
    whatsIncluded: ["300 premium ABS bricks", "Pull-back motor + smoke-effect exhaust", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "300" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~2 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-013",
    slug: "arc-de-triomphe",
    name: "Arc De Triomphe",
    brand: "KraftyBrix",
    category: "Landmarks",
    tagline: "An architectural icon, in brick.",
    description: "The Arc De Triomphe is a collector-grade brick-built model — 900 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 5799,
    salePrice: 2899,
    rating: 5.0,
    reviewCount: 260,
    pieces: 900,
    buildHours: 8,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: true,
    bodyColor: "#C9A24B",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/ARC_ADT_019_1774840892139_n1g90uzl51tjr8q.jpg", alt: "Arc De Triomphe" }],
    whatsIncluded: ["900 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish", "Numbered authenticity card"],
    specs: [{ label: "Pieces", value: "900" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~8 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-014",
    slug: "leaning-tower-of-pisa",
    name: "Leaning Tower of Pisa",
    brand: "KraftyBrix",
    category: "Landmarks",
    tagline: "An architectural icon, in brick.",
    description: "The Leaning Tower of Pisa is a collector-grade brick-built model — 900 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 5799,
    salePrice: 2899,
    rating: 4.8,
    reviewCount: 412,
    pieces: 900,
    buildHours: 8,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: true,
    bodyColor: "#C9A24B",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/ARC_PIS_017_1774840933702_35y2rq6g210o339.jpg", alt: "Leaning Tower of Pisa" }],
    whatsIncluded: ["900 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish", "Numbered authenticity card"],
    specs: [{ label: "Pieces", value: "900" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~8 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-015",
    slug: "tower-bridge",
    name: "Tower Bridge",
    brand: "KraftyBrix",
    category: "Landmarks",
    tagline: "An architectural icon, in brick.",
    description: "The Tower Bridge is a collector-grade brick-built model — 900 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 5799,
    salePrice: 2899,
    rating: 4.9,
    reviewCount: 367,
    pieces: 900,
    buildHours: 8,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: true,
    bodyColor: "#C9A24B",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/ARC_TBR_018_1774840946542_spbc4bu46qavw1c.jpg", alt: "Tower Bridge" }],
    whatsIncluded: ["900 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish", "Numbered authenticity card"],
    specs: [{ label: "Pieces", value: "900" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~8 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-016",
    slug: "dubai-skyline-building-blocks-set",
    name: "Dubai Skyline Building Blocks Set",
    brand: "KraftyBrix",
    category: "Landmarks",
    tagline: "An architectural icon, in brick.",
    description: "The Dubai Skyline Building Blocks Set is a collector-grade brick-built model — 900 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 5799,
    salePrice: 2899,
    rating: 4.7,
    reviewCount: 289,
    pieces: 900,
    buildHours: 8,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: true,
    bodyColor: "#C9A24B",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/ARC_DXB_016_1774840940400_veyleze1b1k48m9.jpg", alt: "Dubai Skyline Building Blocks Set" }],
    whatsIncluded: ["900 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish", "Numbered authenticity card"],
    specs: [{ label: "Pieces", value: "900" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~8 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-017",
    slug: "lambo-huracan-super-trofeo-evo",
    name: "Lambo Huracán Super Trofeo EVO",
    brand: "KraftyBrix",
    category: "Racing Cars",
    tagline: "Track-bred, fully exposed aero.",
    description: "The Lambo Huracán Super Trofeo EVO is a collector-grade brick-built model — 620 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1899,
    salePrice: 1199,
    rating: 4.9,
    reviewCount: 156,
    pieces: 620,
    buildHours: 3,
    difficulty: "Intermediate",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: true,
    limited: false,
    bodyColor: "#E0A21A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/Lambo_Hurac_n_Super_Trofeo_EVO_C1J5NNU82S_2026-04-29_1.png", alt: "Lambo Huracán Super Trofeo EVO" }],
    whatsIncluded: ["620 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "620" }, { label: "Difficulty", value: "Intermediate" }, { label: "Build time", value: "~3 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-018",
    slug: "porsche-911-rsr",
    name: "Porsche 911 RSR",
    brand: "KraftyBrix",
    category: "Racing Cars",
    tagline: "Track-bred, fully exposed aero.",
    description: "The Porsche 911 RSR is a collector-grade brick-built model — 1980 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 3199,
    salePrice: 1999,
    rating: 4.6,
    reviewCount: 98,
    pieces: 1980,
    buildHours: 6,
    difficulty: "Master",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: true,
    isNew: true,
    limited: false,
    bodyColor: "#D8DCE2",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/Eaecb36t_LIPY5LV4V9_2026-04-29_1.png", alt: "Porsche 911 RSR" }],
    whatsIncluded: ["1980 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "1,980" }, { label: "Difficulty", value: "Master" }, { label: "Build time", value: "~6 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-019",
    slug: "lamborghini-sian-fkp-37",
    name: "Lamborghini Sián FKP 37",
    brand: "KraftyBrix",
    category: "Hypercars",
    tagline: "Brick-built hypercar fury.",
    description: "The Lamborghini Sián FKP 37 is a collector-grade brick-built model — 1980 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 3199,
    salePrice: 1999,
    rating: 4.8,
    reviewCount: 204,
    pieces: 1980,
    buildHours: 6,
    difficulty: "Master",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: true,
    limited: false,
    bodyColor: "#E0A21A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/Lamborghini_Si_n_FKP_37_D6V6845Z3A_2026-04-29_1.png", alt: "Lamborghini Sián FKP 37" }],
    whatsIncluded: ["1980 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "1,980" }, { label: "Difficulty", value: "Master" }, { label: "Build time", value: "~6 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-020",
    slug: "ferrari-fxx-k",
    name: "Ferrari FXX K",
    brand: "KraftyBrix",
    category: "Hypercars",
    tagline: "Brick-built hypercar fury.",
    description: "The Ferrari FXX K is a collector-grade brick-built model — 1100 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 3399,
    salePrice: 1699,
    rating: 4.9,
    reviewCount: 176,
    pieces: 1100,
    buildHours: 5,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: true,
    isNew: false,
    limited: false,
    bodyColor: "#D11B2A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/FER_FXX_007_1774840868274_brl68j4pdjr8tw7.jpg", alt: "Ferrari FXX K" }],
    whatsIncluded: ["1100 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "1,100" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~5 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-021",
    slug: "mc-blaze-gt",
    name: "Mc Blaze GT",
    brand: "KraftyBrix",
    category: "Supercars",
    tagline: "A supercar icon, brick by brick.",
    description: "The Mc Blaze GT is a collector-grade brick-built model — 1650 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 3199,
    salePrice: 1599,
    rating: 4.8,
    reviewCount: 243,
    pieces: 1650,
    buildHours: 5,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#FF6A00",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/MCL_BLA_002_1774840872276_86zfsbleav56dsx.jpg", alt: "Mc Blaze GT" }],
    whatsIncluded: ["1650 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "1,650" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~5 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-022",
    slug: "crimson-lightning-smoking-car",
    name: "Crimson Lightning Smoking Car",
    brand: "KraftyBrix",
    category: "Smoking Cars",
    tagline: "Pull-back power with a real smoke-effect exhaust.",
    description: "The Crimson Lightning Smoking Car is a collector-grade brick-built model — 300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1399,
    salePrice: 699,
    rating: 4.7,
    reviewCount: 131,
    pieces: 300,
    buildHours: 2,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#C81025",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/SMK_CRI_020_1774840902490_epxj3p9dsqfysjw.jpg", alt: "Crimson Lightning Smoking Car" }],
    whatsIncluded: ["300 premium ABS bricks", "Pull-back motor + smoke-effect exhaust", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "300" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~2 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-023",
    slug: "sunlight-tracer-smoking-car",
    name: "Sunlight Tracer Smoking Car",
    brand: "KraftyBrix",
    category: "Smoking Cars",
    tagline: "Pull-back power with a real smoke-effect exhaust.",
    description: "The Sunlight Tracer Smoking Car is a collector-grade brick-built model — 300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1399,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 88,
    pieces: 300,
    buildHours: 2,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#D11B2A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/Sunlight_Tracer_Smoking_Car_W5YEV6HHVZ_2026-04-29_1.jpg", alt: "Sunlight Tracer Smoking Car" }],
    whatsIncluded: ["300 premium ABS bricks", "Pull-back motor + smoke-effect exhaust", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "300" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~2 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-024",
    slug: "white-ghost-smoking-car",
    name: "White Ghost Smoking Car",
    brand: "KraftyBrix",
    category: "Smoking Cars",
    tagline: "Pull-back power with a real smoke-effect exhaust.",
    description: "The White Ghost Smoking Car is a collector-grade brick-built model — 300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1399,
    salePrice: 699,
    rating: 4.8,
    reviewCount: 322,
    pieces: 300,
    buildHours: 2,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#D8DCE2",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/White_Ghost_Smoking_Car_LGBHLLWA4I_2026-04-29_1.jpg", alt: "White Ghost Smoking Car" }],
    whatsIncluded: ["300 premium ABS bricks", "Pull-back motor + smoke-effect exhaust", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "300" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~2 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-025",
    slug: "pacific-champion-85-smoking-car",
    name: "Pacific Champion 85 Smoking Car",
    brand: "KraftyBrix",
    category: "Smoking Cars",
    tagline: "Pull-back power with a real smoke-effect exhaust.",
    description: "The Pacific Champion 85 Smoking Car is a collector-grade brick-built model — 300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 1399,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 140,
    pieces: 300,
    buildHours: 2,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#D11B2A",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/Pacific_Champion_85_Smoking_Car_QV1A2BU7OE_2026-04-29_1.png", alt: "Pacific Champion 85 Smoking Car" }],
    whatsIncluded: ["300 premium ABS bricks", "Pull-back motor + smoke-effect exhaust", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "300" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~2 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-026",
    slug: "audi-r8",
    name: "Audi R8",
    brand: "KraftyBrix",
    category: "Supercars",
    tagline: "A supercar icon, brick by brick.",
    description: "The Audi R8 is a collector-grade brick-built model — 240 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 999,
    salePrice: 499,
    rating: 4.7,
    reviewCount: 95,
    pieces: 240,
    buildHours: 1,
    difficulty: "Beginner",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: true,
    limited: false,
    bodyColor: "#C81025",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/Audi_R8_660C0J5OAQ_2026-04-29_1.png", alt: "Audi R8" }],
    whatsIncluded: ["240 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "240" }, { label: "Difficulty", value: "Beginner" }, { label: "Build time", value: "~1 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-027",
    slug: "bmw-bike",
    name: "BMW Bike",
    brand: "KraftyBrix",
    category: "Limited Editions",
    tagline: "Numbered. Rare. Collector-only.",
    description: "The BMW Bike is a collector-grade brick-built model — 1200 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 4999,
    salePrice: 2499,
    rating: 4.9,
    reviewCount: 260,
    pieces: 1200,
    buildHours: 7,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: true,
    isNew: false,
    limited: true,
    bodyColor: "#1466D6",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/BMW_BIK_015_1774840926708_a930owqv237nfzd.jpg", alt: "BMW Bike" }],
    whatsIncluded: ["1200 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish", "Numbered authenticity card"],
    specs: [{ label: "Pieces", value: "1,200" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~7 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-028",
    slug: "tesla-truck-with-trolley-bike",
    name: "Tesla Truck with Trolley & Bike",
    brand: "KraftyBrix",
    category: "Limited Editions",
    tagline: "Numbered. Rare. Collector-only.",
    description: "The Tesla Truck with Trolley & Bike is a collector-grade brick-built model — 1300 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 4999,
    salePrice: 2599,
    rating: 4.6,
    reviewCount: 412,
    pieces: 1300,
    buildHours: 7,
    difficulty: "Advanced",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: true,
    isNew: false,
    limited: true,
    bodyColor: "#AEB4BD",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/Tesla_Truck_with_attached_Trolley___Bike_ECZRP9R9MY_2026-04-29_1.png", alt: "Tesla Truck with Trolley & Bike" }],
    whatsIncluded: ["1300 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish", "Numbered authenticity card"],
    specs: [{ label: "Pieces", value: "1,300" }, { label: "Difficulty", value: "Advanced" }, { label: "Build time", value: "~7 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
  {
    id: "kb-029",
    slug: "tesla-truck",
    name: "Tesla Truck",
    brand: "KraftyBrix",
    category: "SUVs & Trucks",
    tagline: "Conquer the shelf and the trail.",
    description: "The Tesla Truck is a collector-grade brick-built model — 1980 precision ABS pieces capturing every line of the original. Snaps together into a display-ready centrepiece for any desk or shelf.",
    price: 3199,
    salePrice: 1999,
    rating: 4.8,
    reviewCount: 367,
    pieces: 1980,
    buildHours: 6,
    difficulty: "Master",
    ageRange: "14+",
    scale: "Collectible",
    inStock: true,
    bestSeller: false,
    isNew: false,
    limited: false,
    bodyColor: "#AEB4BD",
    accentColor: "#111111",
    images: [{ url: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/69c3df7c3e5bf55ff8da97e9/cat_img/TES_TRK_013_1774840895040_6ydsp020rgex3qq.jpg", alt: "Tesla Truck" }],
    whatsIncluded: ["1980 premium ABS bricks", "Illustrated step-by-step manual", "Sticker pack included", "Display-ready finish"],
    specs: [{ label: "Pieces", value: "1,980" }, { label: "Difficulty", value: "Master" }, { label: "Build time", value: "~6 hrs" }, { label: "Material", value: "ABS bricks" }, { label: "Recommended age", value: "14+" }],
  },
];

export function getProduct(slug: string) { return products.find((p) => p.slug === slug); }
export function getBestSellers() { return products.filter((p) => p.bestSeller); }
export function getByCategory(category: Category) { return products.filter((p) => p.category === category); }

export interface CategoryMeta { name: Category; slug: string; blurb: string; from: string; to: string; }

export const categories: CategoryMeta[] = [
  { name: "Hypercars", slug: "hypercars", blurb: "The bleeding edge of brick engineering.", from: "#0066FF", to: "#062a66" },
  { name: "Supercars", slug: "supercars", blurb: "Everyday icons, dialled to eleven.", from: "#FF2D20", to: "#7a0d06" },
  { name: "Racing Cars", slug: "racing-cars", blurb: "Track-bred thoroughbreds.", from: "#FF2D20", to: "#0066FF" },
  { name: "SUVs & Trucks", slug: "suvs-trucks", blurb: "Luxury that conquers terrain.", from: "#1f6f3f", to: "#0c2a18" },
  { name: "Smoking Cars", slug: "smoking-cars", blurb: "Pull-back power with real smoke effects.", from: "#ff5e3a", to: "#2a0a66" },
  { name: "Landmarks", slug: "landmarks", blurb: "Architectural icons, brick by brick.", from: "#C9A24B", to: "#3a2f0a" },
  { name: "Limited Editions", slug: "limited-editions", blurb: "Numbered. Rare. Yours.", from: "#d4af37", to: "#3a2f0a" },
];

export function categoryCount(name: Category) { return products.filter((p) => p.category === name).length; }

/** First real product photo for a category (for tiles/galleries). */
export function categoryImage(name: Category): string | undefined {
  const inCat = products.filter((p) => p.category === name && p.images[0]?.url?.startsWith("http"));
  return (inCat[0] ?? products.find((p) => p.images[0]?.url?.startsWith("http")))?.images[0]?.url;
}

/** A spread of real product photos for showcase galleries. */
export function galleryImages(count = 8): { url: string; name: string; color: string }[] {
  return products
    .filter((p) => p.images[0]?.url?.startsWith("http"))
    .slice(0, count)
    .map((p) => ({ url: p.images[0].url, name: p.name, color: p.bodyColor }));
}